###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
# @Author   :   Mahasri Kalavala
###############################################################################
homeassistant:
  name: MyHome
  temperature_unit: F
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  unit_system: imperial
  time_zone: !secret time_zone
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml
  packages: !include_dir_named packages

  allowlist_external_dirs:
    - /config/www/downloads/camera/patio/
    - /config/www/downloads/camera/garage/
    - /config/www/downloads/camera/playarea/
    - /config/www/downloads/camera/driveway/
    - /config/www/downloads/camera/frontdoor/
    - /config/www/downloads/camera/kitchen/
    - /config/www/downloads/camera/frontroom/
    - /config/www/downloads/camera/3dprinter/

sun:
alexa:
config:
discovery:
  ignore:
    - homekit

frontend:

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_key

homekit:
  autostart: true
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - switch
      - input_boolean
      - camera
    include_entities:
      - binary_sensor.door_window_sensor_158d00040ad8fc # Back Door
      - binary_sensor.door_window_sensor_158d000424a6d6 # Front Door
      - binary_sensor.door_window_sensor_158d0004248d5b # Single Car Garage
      - binary_sensor.door_window_sensor_158d0004231f7b # Double Car Garage
      - binary_sensor.door_window_sensor_158d0004880f30 # Garage Entry Door

mobile_app:
# default_config:
websocket_api:
python_script:
logger: !include logging.yaml
zeroconf:
system_health:

life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password
  circles:
    include: [Family]

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 60
  client_id: HA_SERVER

sonos:
  media_player:
    hosts:
      - !secret sonos_living_room_ip
      - !secret sonos_front_room_ip

binary_sensor:
  - platform: workday
    country: US

lovelace:
  mode: yaml
  resources:
    - url: /local/button-card.js
      type: module

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
#emulated_hue:
#  expose_by_default: false
#  host_ip: !secret ha_ip_address
#  listen_port: 8300
#  exposed_domains:
#    - light
#    - switch
#    - input_boolean
#    - group
