default: warning
logs:
  gsp: critical
  root: warning
  pyhap: warning
  openzwave: warning
  py.warnings: warning
  pywemo.ssdp: warning
  libopenzwave: warning
  simplipy.api: warning
  netdisco.ssdp: warning
  aiohttp.server: warning
  aiohttp.websocket: error
  homeassistant.core: critical
  homeassistant.setup: warning
  homeassistant.loader: warning # hide custom_component warnings
  homeassistant.exceptions: warning
  homeassistant.helpers.script: warning
  homeassistant.helpers.entity: warning
  homeassistant.components.wemo: critical
  homeassistant.components.sensor: critical
  homeassistant.components.cloud.iot: warning
  # homeassistant.components.http: warning
  homeassistant.components.camera: warning
  homeassistant.components.zwave: critical
  homeassistant.components.image_processing: warning
  homeassistant.components.homekit: warning
  custom_components.sensor.life360: warning
  custom_components.sensor.paloalto: warning
  homeassistant.components.recorder: warning
  homeassistant.components.discovery: warning
  homeassistant.components.automation: warning
  custom_components.sensor.command_line: warning
  homeassistant.components.climate.nest: warning
  homeassistant.components.media_player: warning
  custom_components.media_player.sharptv: warning
  homeassistant.components.switch.tplink: warning
  homeassistant.components.emulated_hue: warning
  homeassistant.components.device_tracker: warning
  homeassistant.components.camera.generic: warning
  homeassistant.components.automation.update_zwave_battery_levels: critical
