###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Home Assistant
#   @description    :   Bunch of Sensors that are system or environment related
###############################################################################
homeassistant:

shell_command:
  stop_hass: >-
    hassctl stop

  restart_hass: >-
    hassctl restart

  update_hass: >-
    hassctl update-hass && hassctl config && hassctl restart

speedtestdotnet:
  scan_interval:
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload

sensor:
  - platform: uptime
    name: Home Assistant Up Time
    unit_of_measurement: hours

  - platform: rest
    resource: http://icanhazip.com
    name: external_ip
    value_template: "{{ value }}"
    scan_interval: 86400

  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: ens160
      - type: last_boot

  - platform: mqtt
    state_topic: "iotlink/domain/winsvr2016/lwt"
    name: "Windows Server"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "iotlink/domain/winsvr2016/windows-monitor/stats/cpu/usage"
    name: "Windows Server CPU Usage"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "iotlink/domain/winsvr2016/windows-monitor/stats/memory/used"
    name: "Windows Server Memory Used"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "iotlink/domain/winsvr2016/windows-monitor/stats/memory/available"
    name: "Windows Server Memory Available"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "iotlink/domain/winsvr2016/windows-monitor/stats/system/idle-time"
    name: "Windows Server Idle Time"
    value_template: "{{ value }}"
